### ISSUE TITLE
provide available configurations (what the user can write in the yaml file) in the docs 

### ISSUE THREAD

**Issue by nidhaloff** [nidhaloff/igel#22]
### Description

This issue is about providing the configurations in the docs that the user can use in the yaml file. This includes a description of what each key/value pairs can do. At the moment I just wrote these in the Readme file but it would be great to have an overview about it in the docs. I think this would be a great issue for new comers

**Comment by iptizer** [comment]
Maybe just adding a very extensive example would be sufficient. In a small tryout yesterday we have not been able to get it running, as it is totally unclear how to specify things in the yaml.

i.e. dtype or usecols - As a map or a list or a comma seperated list...

**Comment by nidhaloff** [comment]
@iptizer Sorry to hear that! I will definetly look this up and improve the readme/docs ASAP
