### ISSUE TITLE
Add docker support

### ISSUE THREAD

**Issue by nidhaloff** [nidhaloff/igel#36]
### Description

create a docker image so that people can just docker pull the igel container and therefore they can use igel without installing anything.

If someone wants to contribute and work on this, then feel free to create a docker folder in the repo and work on this feature there

**Comment by matt-ross16** [comment]
I'll work on getting a docker image set up

**Comment by nidhaloff** [comment]
@matt-ross16 great, thanks for joining ;)

**Comment by nidhaloff** [comment]
@matt-ross16 Hi, is everything alright? do you have any updates? I'm just checking if you are still working on this

**Comment by matt-ross16** [comment]
Yes, apologies. I'm getting back on this horse right now. Life got in the way a bit. Hopefully I can solve this issue quick, and get this running

**Comment by matt-ross16** [comment]
Ok, I see where I left of. In the process of installing, I was following your CONTRIBUTING doc, and ran into issues at this step:
 
![image](https://user-images.githubusercontent.com/37879416/96144709-77288f80-0ed2-11eb-9250-aacf5cd44b7c.png)

I have my virtual environment set up, but when I attempt to setup igel, I get this error:

![image](https://user-images.githubusercontent.com/37879416/96145040-cbcc0a80-0ed2-11eb-8176-a779016891f6.png)

Is there something I'm missing in the setup process?

**Comment by nidhaloff** [comment]
@matt-ross16 Thanks for the update. I assume you have python < 3.6 that's why it didn't understand the f string syntax. Did you created a virtualenv with python>=3.6 ? if not then you can use this command `python3.8 -m venv env` instead of `virtualenv igel` .

Then activate it using `source env/bin/activate` (this can be different on windows but you can just google it).

**Comment by matt-ross16** [comment]
I was wondering if it was due to my version of Python! Thanks for the quick reply :) I'll try this out

**Comment by nidhaloff** [comment]
@matt-ross16 someone just made a pull request now for this issue. I actually thought it was you! You can work further on improving this, just go ahead and check what it new in the repo ;)

**Comment by matt-ross16** [comment]
No worries! I'll look into the new PR and try to figure out what I was missing. Thanks for your help regardless! :)
