### ISSUE TITLE
provide support for other input format

### ISSUE THREAD

**Issue by nidhaloff** [nidhaloff/igel#37]
### Description

In the future, igel should support multiple dataset format other than csv. Maybe add support for excel, json and sql tables.

It would be great if users have the flexibility of providing their datasets in other formats and not only csv. 

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

If you want to work on this, please consider using pandas because It's already a dependency in igel. Not adding unnecessary dependencies is important, so considering check it out whether this can be achieved using pandas. Otherwise, we can discuss adding an additional library in the comments

**Comment by dinhanhx** [comment]
For anyone who is interested in doing this, I suggest check out this https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html
