### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by GouravWadhwa** [nidhaloff/igel#75]
* igel version:0.4.0
* Python version:3.8
* Operating System:MacOS

### Description

In the Contributing Guide it is written to run poetry run tests which might be wrong and should be changed to poetry run pytest. Further running poetry run pytest also results in error even for the current code

<img width="1439" alt="Screenshot 2021-08-21 at 10 43 13 PM" src="https://user-images.githubusercontent.com/62446812/130329777-7606ed92-6e7f-4c18-8a0d-ead61c78debe.png">

**Comment by GouravWadhwa** [comment]
This might be happening because model results are being saved at ./igel/model_results whereas in assert command it trying to check whether the results are stored at ./igel/tests/test_igel/model_results
I think this can be solved by changing the path in constants file.

**Comment by nidhaloff** [comment]
Hi, the right command for running test is "make test". I will fix this in
the docs.
