### ISSUE TITLE
Add RNN/LSTM support

### ISSUE THREAD

**Issue by nidhaloff** [nidhaloff/igel#78]
### Description

We want to add support for RNNs. I will let this issue open for people who want to contribute to this project. 
My suggestion would be just to write RNN (or any other RNN-like model) in the algorithm field in order to use an RNN model. Here is an example to illustrate what I mean:

```
model:
     type: classification
     algorithm: RNN
    .
    . 

```

**If you are willing to work on this, please just start and don't wait for my approval.**
Anyone is free to join the [discussion](https://github.com/nidhaloff/igel/discussions/80) to share ideas.

**Comment by pragyasrivastava0805** [comment]
@nidhaloff ,I am very new to open source,I want to start working on this.Could you please walk me through the process

**Comment by nidhaloff** [comment]
@pragyasrivastava0805 did you read the docs? https://igel.readthedocs.io/en/latest/contributing.html or https://github.com/nidhaloff/igel/blob/master/CONTRIBUTING.rst

also, there is a discussion for this issue here: https://github.com/nidhaloff/igel/discussions/80

**Comment by GouravWadhwa** [comment]
Hi @nidhaloff, I have written run implementation for for RNN in pytorch. Please let me know if there is some dataset with which I can test my algorithm.
I have implemented user defined rnn's which can be used for classification.
