### ISSUE TITLE
added tests

### ISSUE THREAD

**Issue by nidhaloff** [nidhaloff/igel#9]
### Description
added some tests to test the functionality of igel

**Comment by dinhanhx** [comment]
What I can do for you?

**Comment by nidhaloff** [comment]
@dinhanhx Thanks for joining. As I stated in the title, I let this open as a good first issue for new comers to start write some unit tests (or any kind of test actually). I started the project recently so it still under heavy development. I was mainly busy implementing features in my little free time. 

This issue is about writing some basic tests. So, you can start writing some basic tests under the test folder in the repo. If you read the docs, you will find that I'm using (or want to use) [pytest](https://docs.pytest.org/en/stable/) as a test package but you can actually use anything that you are comfortable with (like the integrated unittest module in python)

**Comment by dinhanhx** [comment]
Okay I understand what you say, do you have class diagram for this project?

**Comment by nidhaloff** [comment]
@dinhanhx Unfortunately no for now.
